### ISSUE TITLE
我的docker镜像是基于paddlepaddle的，使用的是cpu，但是报cuda的错误

### ISSUE THREAD

**Issue by frozenfires** [PaddlePaddle/DeepSpeech#215]
我自己制作的deepspeech2镜像，已经设置use_gpu=False，demo_server启动成功。但是，识别时会报Cuda Error。帮帮我！

Received utterance[length=98304] from 172.17.0.1, saved to demo_cache/20180419115913_172.17.0.1.wav.
F0419 11:59:16.257073   178 hl_cuda_device.cc:565] Check failed: cudaSuccess == cudaStat (0 vs. 35) Cuda Error: CUDA driver version is insufficient for CUDA runtime version
*** Check failure stack trace: ***
    @     0x7f62e287927d  google::LogMessage::Fail()
    @     0x7f62e287cd2c  google::LogMessage::SendToLog()
    @     0x7f62e2878da3  google::LogMessage::Flush()
    @     0x7f62e287e23e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f62e2833673  hl_stream_synchronize()
    @     0x7f62e246bae7  paddle::SubSequenceLayer::forward()
    @     0x7f62e259802d  paddle::NeuralNetwork::forward()
    @     0x7f62e24235dd  _wrap_GradientMachine_forward
    @           0x4c30ce  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c1e6f  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c1e6f  PyEval_EvalFrameEx
    @           0x4d4c9d  (unknown)
    @           0x4bc9b6  PyEval_EvalFrameEx
    @           0x4d4c9d  (unknown)
    @           0x4bc9b6  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c16e7  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c1e6f  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c1e6f  PyEval_EvalFrameEx
    @           0x4c136f  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4d54b9  (unknown)
    @           0x4eebee  (unknown)
    @           0x4a577e  PyObject_Call
    @           0x4d8f92  PyInstance_New
    @           0x4c15bf  PyEval_EvalFrameEx
    @           0x4c136f  PyEval_EvalFrameEx
    @           0x4c136f  PyEval_EvalFrameEx
Aborted (core dumped)
Failed in starting demo server!

如果有cpu版本的镜像，那就更好了

**Comment by gangyahaidao** [comment]
Paddle在编译的时候开启了GPU选项吧，或者用的paddle镜像是GPU版本的

**Comment by frozenfires** [comment]
谢谢了，果然是paddlepaddle的问题，我卸载重装就好了

**Comment by llp123** [comment]
@frozenfires 你好能否分享一下你的cpu版本的docker，谢谢。2385114637@qq.com

**Comment by frozenfires** [comment]
@llp123 这个项目都废弃了，你要的话直接拉取 docker pull frozenfires/deepspeech-cpu，hub上有使用方法

**Comment by llp123** [comment]
@frozenfires 谢谢，已经构建完自己的docker了，不需要了

**Comment by hui001** [comment]
@llp123 你好，请问可以分享一下构建cpu版本docker的过程么？  @frozenfires  现在这个镜像是不是不存在了？我拉取不下来。谢谢。

**Comment by wanwanzaizai** [comment]
@frozenfires 你好，我遇到跟你一样的问题了，请问你重装paddlepaddle是pip直接装的还是源码安装的
